### ISSUE TITLE
Option to show playlist song artwork icons?

### ISSUE THREAD

**Issue by MJ-asa** [szymonszewcjr/legacyLook#2]
Is there a way to have the album art for a song show in a playlist

**Comment by szymonszewcjr** [comment]
I'm currently rewriting whole extension from scratch, and all tweaks will be toggleable. So you will be able to customize your spotify client exactly how you see fit.

**Comment by szymonszewcjr** [comment]
This repo will not be updated, this project has been moved to [https://github.com/szymonszewcjr/LegacyTweaks](https://github.com/szymonszewcjr/LegacyTweaks). It is rewritten from scratch and much easier to configure.
And I have an option to show album art in playlists reimplemented again.
